const VOICING_LIBRARY = {
    'C': {
        'Major': [{ fret: null, finger: 'X' }, { fret: 2, finger: '3' }, { fret: 1, finger: '2' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }],
        'Minor': [{ fret: null, finger: 'X' }, { fret: 2, finger: '1' }, { fret: 4, finger: '3' }, { fret: 4, finger: '4' }, { fret: 3, finger: '2' }, { fret: 2, finger: '1' }],
        'Dominant 7th': [{ fret: null, finger: 'X' }, { fret: 2, finger: '2' }, { fret: 1, finger: '1' }, { fret: 2, finger: '3' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }],
        'Major 7th': [{ fret: null, finger: 'X' }, { fret: 2, finger: '2' }, { fret: 1, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }],
        'Minor 7th': [{ fret: null, finger: 'X' }, { fret: 2, finger: '1' }, { fret: 4, finger: '3' }, { fret: 2, finger: '1' }, { fret: 3, finger: '2' }, { fret: 2, finger: '1' }],
        'Major 6th': [{ fret: null, finger: 'X' }, { fret: 2, finger: '3' }, { fret: 1, finger: '2' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: null, finger: 'X' }],
        'Minor 6th': [{ fret: null, finger: 'X' }, { fret: 2, finger: '4' }, { fret: 0, finger: '1' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: null, finger: 'X' }],
        'Diminished': [{ fret: null, finger: 'X' }, { fret: 2, finger: '1' }, { fret: 3, finger: '2' }, { fret: 4, finger: '4' }, { fret: 3, finger: '3' }, { fret: null, finger: 'X' }],
        'Suspended 4th': [{ fret: null, finger: 'X' }, { fret: 2, finger: '2' }, { fret: 2, finger: '3' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: null, finger: 'X' }],
        'Dominant 9th': [{ fret: null, finger: 'X' }, { fret: 2, finger: '1' }, { fret: 1, finger: '1' }, { fret: 2, finger: '2' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }],
        'Augmented': [{ fret: null, finger: 'X' }, { fret: 2, finger: '3' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: null, finger: 'X' }]
    },
    'C#': {
        'Major': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 5, finger: '4' }, { fret: 5, finger: '2' }, { fret: 3, finger: '1' }],
        'Minor': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 5, finger: '4' }, { fret: 4, finger: '2' }, { fret: 3, finger: '1' }],
        'Dominant 7th': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 3, finger: '1' }, { fret: 5, finger: '4' }, { fret: 3, finger: '1' }],
        'Major 7th': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 4, finger: '2' }, { fret: 5, finger: '4' }, { fret: 3, finger: '1' }],
        'Minor 7th': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 3, finger: '1' }, { fret: 4, finger: '2' }, { fret: 3, finger: '1' }],
        'Major 6th': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '2' }, { fret: 5, finger: '2' }, { fret: 5, finger: '2' }, { fret: 5, finger: '2' }],
        'Minor 6th': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 5, finger: '4' }, { fret: 4, finger: '2' }, { fret: 5, finger: '1' }],
        'Diminished': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 4, finger: '2' }, { fret: 5, finger: '4' }, { fret: 4, finger: '3' }, { fret: null, finger: 'X' }],
        'Suspended 4th': [{ fret: null, finger: 'X' }, { fret: 3, finger: '1' }, { fret: 5, finger: '2' }, { fret: 5, finger: '3' }, { fret: 6, finger: '4' }, { fret: 3, finger: '1' }],
        'Dominant 9th': [{ fret: null, finger: 'X' }, { fret: 3, finger: '2' }, { fret: 2, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 3, finger: '4' }],
        'Augmented': [{ fret: null, finger: 'X' }, { fret: 3, finger: '4' }, { fret: 2, finger: '3' }, { fret: 1, finger: '1' }, { fret: 1, finger: '2' }, { fret: null, finger: 'X' }]
    },
    'D': {
        'Major': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '1' }, { fret: 2, finger: '3' }, { fret: 1, finger: '2' }],
        'Minor': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 2, finger: '3' }, { fret: 0, finger: '1' }],
        'Dominant 7th': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 1, finger: '3' }],
        'Major 7th': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '1' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }],
        'Minor 7th': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }],
        'Major 6th': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '3' }],
        'Minor 6th': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '3' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }],
        'Diminished': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '2' }],
        'Suspended 4th': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '1' }, { fret: 2, finger: '2' }, { fret: 2, finger: '3' }],
        'Dominant 9th': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }],
        'Augmented': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 2, finger: '2' }, { fret: 2, finger: '3' }, { fret: 1, finger: '1' }]
    },
    'D#': {
        'Major': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '3' }, { fret: 7, finger: '4' }, { fret: 7, finger: '2' }, { fret: 5, finger: '1' }],
        'Minor': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '3' }, { fret: 7, finger: '4' }, { fret: 6, finger: '2' }, { fret: 5, finger: '1' }],
        'Dominant 7th': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '3' }, { fret: 5, finger: '1' }, { fret: 7, finger: '4' }, { fret: 5, finger: '1' }],
        'Major 7th': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '3' }, { fret: 6, finger: '2' }, { fret: 7, finger: '4' }, { fret: 5, finger: '1' }],
        'Minor 7th': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '3' }, { fret: 5, finger: '1' }, { fret: 6, finger: '2' }, { fret: 5, finger: '1' }],
        'Major 6th': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '2' }, { fret: 7, finger: '2' }, { fret: 7, finger: '2' }, { fret: 7, finger: '2' }],
        'Minor 6th': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '3' }, { fret: 7, finger: '4' }, { fret: 6, finger: '2' }, { fret: 7, finger: '1' }],
        'Diminished': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 1, finger: '3' }, { fret: 0, finger: '2' }, { fret: 1, finger: '4' }],
        'Suspended 4th': [{ fret: null, finger: 'X' }, { fret: 5, finger: '1' }, { fret: 7, finger: '2' }, { fret: 7, finger: '3' }, { fret: 8, finger: '4' }, { fret: 5, finger: '1' }],
        'Dominant 9th': [{ fret: null, finger: 'X' }, { fret: 5, finger: '2' }, { fret: 4, finger: '1' }, { fret: 5, finger: '3' }, { fret: 5, finger: '4' }, { fret: 5, finger: '4' }],
        'Augmented': [{ fret: null, finger: 'X' }, { fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: null, finger: 'X' }]
    },
    'E': {
        'Major': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }],
        'Minor': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }],
        'Dominant 7th': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }],
        'Major 7th': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }],
        'Minor 7th': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '1' }, { fret: 1, finger: '2' }, { fret: -1, finger: 'O' }, { fret: 2, finger: '3' }, { fret: -1, finger: 'O' }],
        'Major 6th': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: 0, finger: '1' }, { fret: 1, finger: '4' }, { fret: -1, finger: 'O' }],
        'Minor 6th': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '4' }, { fret: -1, finger: 'O' }],
        'Diminished': [{ fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: 1, finger: '3' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '4' }, { fret: -1, finger: 'O' }],
        'Suspended 4th': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: 1, finger: '4' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }],
        'Dominant 9th': [{ fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '3' }],
        'Augmented': [{ fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: null, finger: 'X' }, { fret: null, finger: 'X' }]
    },
    'F': {
        'Major': [{ fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }],
        'Minor': [{ fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }],
        'Dominant 7th': [{ fret: 0, finger: '1' }, { fret: 2, finger: '1' }, { fret: 0, finger: '2' }, { fret: 1, finger: '3' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }],
        'Major 7th': [{ fret: 0, finger: '1' }, { fret: 2, finger: '1' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }],
        'Minor 7th': [{ fret: 0, finger: '1' }, { fret: 2, finger: '1' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }],
        'Major 6th': [{ fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 1, finger: '2' }, { fret: 2, finger: '?' }, { fret: 0, finger: '1' }],
        'Minor 6th': [{ fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 0, finger: '1' }, { fret: 2, finger: '?' }, { fret: 0, finger: '1' }],
        'Diminished': [{ fret: 0, finger: '1' }, { fret: 1, finger: '2' }, { fret: 2, finger: '3' }, { fret: 0, finger: '1' }, { fret: 2, finger: '4' }, { fret: 0, finger: '1' }],
        'Suspended 2nd': [{ fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 2, finger: '2' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }],
        'Suspended 4th': [{ fret: 0, finger: '1' }, { fret: 2, finger: '1' }, { fret: 2, finger: '1' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }]
    },
    'F#': {
        'Major': [{ fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 2, finger: '2' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }],
        'Minor': [{ fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }],
        'Dominant 7th': [{ fret: 1, finger: '1' }, { fret: 3, finger: '1' }, { fret: 1, finger: '2' }, { fret: 2, finger: '3' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }],
        'Major 7th': [{ fret: 1, finger: '1' }, { fret: 3, finger: '1' }, { fret: 2, finger: '2' }, { fret: 2, finger: '3' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }],
        'Minor 7th': [{ fret: 1, finger: '1' }, { fret: 3, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }],
        'Major 6th': [{ fret: 1, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }, { fret: 2, finger: '2' }, { fret: 3, finger: '4' }, { fret: 1, finger: '1' }],
        'Minor 6th': [{ fret: 1, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }, { fret: 1, finger: '1' }, { fret: 3, finger: '4' }, { fret: 1, finger: '1' }],
        'Diminished': [{ fret: 1, finger: '1' }, { fret: 2, finger: '2' }, { fret: 3, finger: '3' }, { fret: 1, finger: '1' }, { fret: 3, finger: '4' }, { fret: 1, finger: '1' }],
        'Suspended 2nd': [{ fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 3, finger: '2' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }],
        'Suspended 4th': [{ fret: 1, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }]
    },
    'G': {
        'Major': [{ fret: 2, finger: '2' }, { fret: 1, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: 2, finger: '3' }],
        'Minor': [{ fret: 2, finger: '1' }, { fret: 4, finger: '3' }, { fret: 4, finger: '4' }, { fret: 2, finger: '1' }, { fret: 2, finger: '1' }, { fret: 2, finger: '1' }],
        'Dominant 7th': [{ fret: 2, finger: '2' }, { fret: 1, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: 0, finger: 'T' }],
        'Major 7th': [{ fret: 2, finger: '2' }, { fret: 1, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '3' }],
        'Minor 7th': [{ fret: 2, finger: '1' }, { fret: 4, finger: '1' }, { fret: 2, finger: '2' }, { fret: 2, finger: '3' }, { fret: 2, finger: '1' }, { fret: 2, finger: '1' }],
        'Major 6th': [{ fret: 2, finger: '2' }, { fret: 1, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: 2, finger: '4' }, { fret: 2, finger: '3' }],
        'Minor 6th': [{ fret: 2, finger: '1' }, { fret: 4, finger: '1' }, { fret: 2, finger: '2' }, { fret: 2, finger: '1' }, { fret: 4, finger: '4' }, { fret: 2, finger: '1' }],
        'Diminished': [{ fret: 2, finger: '2' }, { fret: 3, finger: '3' }, { fret: 1, finger: '1' }, { fret: 2, finger: '4' }, { fret: null, finger: 'X' }, { fret: null, finger: 'X' }],
        'Suspended 2nd': [{ fret: 2, finger: '1' }, { fret: 4, finger: '3' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: 2, finger: '2' }],
        'Suspended 4th': [{ fret: 2, finger: '2' }, { fret: 0, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: 2, finger: '3' }]
    },
    'G#': {
        'Major': [{ fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 5, finger: '4' }, { fret: 4, finger: '2' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }],
        'Minor': [{ fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 5, finger: '4' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }],
        'Dominant 7th': [{ fret: 3, finger: '1' }, { fret: 5, finger: '1' }, { fret: 3, finger: '2' }, { fret: 4, finger: '3' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }],
        'Major 7th': [{ fret: 3, finger: '1' }, { fret: 5, finger: '1' }, { fret: 4, finger: '2' }, { fret: 4, finger: '3' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }],
        'Minor 7th': [{ fret: 3, finger: '1' }, { fret: 5, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }],
        'Major 6th': [{ fret: 3, finger: '1' }, { fret: 5, finger: '1' }, { fret: 5, finger: '1' }, { fret: 4, finger: '2' }, { fret: 5, finger: '4' }, { fret: 3, finger: '1' }],
        'Minor 6th': [{ fret: 3, finger: '1' }, { fret: 5, finger: '1' }, { fret: 5, finger: '1' }, { fret: 3, finger: '1' }, { fret: 5, finger: '4' }, { fret: 3, finger: '1' }],
        'Diminished': [{ fret: 3, finger: '2' }, { fret: 4, finger: '3' }, { fret: 2, finger: '1' }, { fret: 3, finger: '4' }, { fret: null, finger: 'X' }, { fret: null, finger: 'X' }],
        'Suspended 2nd': [{ fret: 3, finger: '1' }, { fret: 5, finger: '3' }, { fret: 5, finger: '4' }, { fret: 5, finger: '2' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }],
        'Suspended 4th': [{ fret: 3, finger: '1' }, { fret: 5, finger: '1' }, { fret: 5, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }, { fret: 3, finger: '1' }]
    },
    'A': {
        'Major': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: 1, finger: '4' }, { fret: -1, finger: 'O' }],
        'Minor': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 1, finger: '3' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }],
        'Dominant 7th': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '3' }, { fret: -1, finger: 'O' }],
        'Major 7th': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 1, finger: '3' }, { fret: -1, finger: 'O' }],
        'Minor 7th': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }],
        'Major 6th': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }, { fret: 1, finger: '1' }],
        'Minor 6th': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '3' }, { fret: 1, finger: '4' }, { fret: 0, finger: '2' }, { fret: 1, finger: '1' }],
        'Diminished': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 0, finger: '1' }, { fret: 1, finger: '3' }, { fret: 0, finger: '2' }, { fret: null, finger: 'X' }],
        'Suspended 4th': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '1' }, { fret: 1, finger: '2' }, { fret: 2, finger: '3' }, { fret: -1, finger: 'O' }],
        'Dominant 9th': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: -1, finger: 'O' }],
        'Augmented': [{ fret: null, finger: 'X' }, { fret: -1, finger: 'O' }, { fret: 2, finger: '3' }, { fret: 1, finger: '1' }, { fret: 1, finger: '2' }, { fret: 0, finger: 'T' }]
    },
    'A#': {
        'Major': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 2, finger: '2' }, { fret: 0, finger: '1' }],
        'Minor': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }],
        'Dominant 7th': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 0, finger: '1' }, { fret: 2, finger: '4' }, { fret: 0, finger: '1' }],
        'Major 7th': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 1, finger: '2' }, { fret: 2, finger: '4' }, { fret: 0, finger: '1' }],
        'Minor 7th': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 0, finger: '1' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }],
        'Major 6th': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '2' }, { fret: 2, finger: '2' }, { fret: 2, finger: '2' }, { fret: 2, finger: '2' }],
        'Minor 6th': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: 1, finger: '2' }, { fret: 2, finger: '1' }],
        'Diminished': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 1, finger: '2' }, { fret: 2, finger: '4' }, { fret: 1, finger: '3' }, { fret: null, finger: 'X' }],
        'Suspended 4th': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: 2, finger: '2' }, { fret: 2, finger: '3' }, { fret: 3, finger: '4' }, { fret: 0, finger: '1' }],
        'Augmented': [{ fret: null, finger: 'X' }, { fret: 0, finger: '1' }, { fret: -1, finger: 'O' }, { fret: 2, finger: '3' }, { fret: 2, finger: '4' }, { fret: null, finger: 'X' }]
    },
    'B': {
        'Major': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 3, finger: '2' }, { fret: 1, finger: '1' }],
        'Minor': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 2, finger: '2' }, { fret: 1, finger: '1' }],
        'Dominant 7th': [{ fret: null, finger: 'X' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 1, finger: '3' }, { fret: -1, finger: 'O' }, { fret: 1, finger: '4' }],
        'Major 7th': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 2, finger: '2' }, { fret: 3, finger: '4' }, { fret: 1, finger: '1' }],
        'Minor 7th': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 3, finger: '4' }, { fret: 1, finger: '1' }, { fret: 2, finger: '3' }, { fret: 1, finger: '1' }],
        'Major 6th': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 3, finger: '2' }, { fret: 3, finger: '2' }, { fret: 3, finger: '2' }, { fret: 3, finger: '2' }],
        'Minor 6th': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 2, finger: '2' }, { fret: 3, finger: '1' }],
        'Diminished': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 2, finger: '2' }, { fret: 3, finger: '4' }, { fret: 2, finger: '3' }, { fret: null, finger: 'X' }],
        'Suspended 4th': [{ fret: null, finger: 'X' }, { fret: 1, finger: '1' }, { fret: 3, finger: '3' }, { fret: 3, finger: '4' }, { fret: 4, finger: '2' }, { fret: 1, finger: '1' }],
        'Dominant 9th': [{ fret: null, finger: 'X' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 1, finger: '3' }, { fret: 1, finger: '4' }, { fret: 1, finger: '4' }],
        'Augmented': [{ fret: null, finger: 'X' }, { fret: 1, finger: '2' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: 0, finger: '1' }, { fret: null, finger: 'X' }]
    }
};
